using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using Framework.UI;

/// <summary>
/// UIBinder 自定义编辑器 —— Refresh 扫描控件 + Export Code 生成 Comps
/// </summary>
[CustomEditor(typeof(UIBinder))]
public class UIBinderEditor : Editor
{
    public override void OnInspectorGUI()
    {
        var binder = (UIBinder)target;

        // Refresh 按钮
        EditorGUILayout.BeginHorizontal();
        if (GUILayout.Button("Refresh", GUILayout.Height(25)))
        {
            Undo.RecordObject(binder, "UIBinder Refresh");
            binder.Refresh();
            EditorUtility.SetDirty(binder);
        }

        GUI.enabled = binder.uiComps.Count > 0;
        if (GUILayout.Button("Export Code", GUILayout.Height(25)))
        {
            ExportCode(binder);
        }
        GUI.enabled = true;
        EditorGUILayout.EndHorizontal();

        if (binder.uiComps.Count == 0)
        {
            EditorGUILayout.HelpBox(
                "命名约定：btn_xxx / txt_xxx / img_xxx / mod_xxx / tog_xxx / sld_xxx / list_xxx\n" +
                "点击 Refresh 自动扫描子物体",
                MessageType.Info);
        }

        EditorGUILayout.Space();

        // 列表只读展示
        EditorGUI.BeginDisabledGroup(true);
        DrawDefaultInspector();
        EditorGUI.EndDisabledGroup();
    }

    private void ExportCode(UIBinder binder)
    {
        if (binder.uiComps.Count == 0)
        {
            Debug.LogError("[UIBinder] uiComps 列表为空，请先点击 Refresh");
            return;
        }

        // 检查有效引用
        var entries = new List<UICompEntry>();
        var names = new HashSet<string>();
        foreach (var e in binder.uiComps)
        {
            if (e.component == null)
            {
                Debug.LogError($"[UIBinder] 控件 '{e.fieldName}' 引用丢失，请重新 Refresh");
                return;
            }
            if (!names.Add(e.fieldName))
            {
                Debug.LogError($"[UIBinder] 字段名重复: '{e.fieldName}'");
                return;
            }
            entries.Add(e);
        }

        // 找到面板/模组/列表项脚本
        var component = binder.GetComponent<BasePanel>()
            ?? (Component)binder.GetComponent<BaseModule>()
            ?? binder.GetComponent<BaseListItem>();
        if (component == null)
        {
            Debug.LogError("[UIBinder] 未找到 BasePanel / BaseModule / BaseListItem 组件！");
            return;
        }

        string typeName = component.GetType().Name;
        string scriptPath = FindScriptPath(component.GetType());
        if (string.IsNullOrEmpty(scriptPath))
        {
            Debug.LogError($"[UIBinder] 找不到 {typeName}.cs");
            return;
        }

        string genCode = GenerateCompsCode(typeName, entries);
        string genPath = scriptPath.Replace(".cs", ".gen.cs");
        File.WriteAllText(genPath, genCode, Encoding.UTF8);

        AssetDatabase.Refresh();
        var fieldList = string.Join(", ", entries.ConvertAll(e => e.fieldName));
        EditorUtility.DisplayDialog("Export Success",
            $"生成 {typeName}.gen.cs\n\n{entries.Count} 个控件：\n{fieldList}", "OK");
    }

    private string GenerateCompsCode(string panelTypeName, List<UICompEntry> entries)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Auto-generated by UIBinder, do not edit manually");
        sb.AppendLine("// Regenerate by clicking \"Export Code\" on UIBinder component");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.UI;");
        sb.AppendLine("using TMPro;");
        sb.AppendLine("using Framework.UI;");
        sb.AppendLine();

        sb.AppendLine($"public partial class {panelTypeName}");
        sb.AppendLine("{");
        sb.AppendLine("    [System.NonSerialized] public CompsData comps = new CompsData();");
        sb.AppendLine();
        sb.AppendLine("    [System.Serializable]");
        sb.AppendLine("    public class CompsData : CompsDataBase");
        sb.AppendLine("    {");

        foreach (var e in entries)
        {
            string type = e.prefix switch
            {
                "btn" => "Button",
                "txt" => "TMP_Text",
                "img" => "Image",
                "mod" => e.typeName ?? "BaseModule",
                "tog" => "Toggle",
                "sld" => "Slider",
                "list" => "ScrollList",
                _ => "Component"
            };
            sb.AppendLine($"        public {type} {e.fieldName};");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private string FindScriptPath(System.Type type)
    {
        var guids = AssetDatabase.FindAssets($"t:MonoScript {type.Name}");
        foreach (var guid in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            if (path.EndsWith($"/{type.Name}.cs"))
                return path;
        }
        return null;
    }
}

