// Auto-generated by UIBinder, do not edit manually
// Regenerate by clicking "Export Code" on UIBinder component

using UnityEngine;
using UnityEngine.UI;
using TMPro;
using Framework.UI;

public partial class MainTopPanel
{
    [System.NonSerialized] public CompsData comps = new CompsData();

    [System.Serializable]
    public class CompsData : CompsDataBase
    {
        public TMP_Text txtLevelProgress;
        public Button btnCardBuild;
        public Button btnMenu;
        public TMP_Text txtLevelInfo;
        public TMP_Text txtCoinInfo;
    }
}
