// Auto-generated by ConfigExporter

[System.Serializable]
public class CardConfig
{
    public string Id;
    public string Image;
    public int Suit;
    public int Rank;
    public int Price;
    public bool SingleGrab;
    public bool AnyTarget;
    public int PlaceSkill;
}
