// Auto-generated by ConfigExporter

[System.Serializable]
public class LevelConfig
{
    public string Id;
    public int LevelType;
    public int FinishReward;
    public int ColumnNum;
    public int PocketNum;
    public string NextLevelId;
    public int NeedStraightNum;
    public int LevelEvent;
}
