// Auto-generated by UIBinder, do not edit manually
// Regenerate by clicking "Export Code" on UIBinder component

using UnityEngine;
using UnityEngine.UI;
using TMPro;
using Framework.UI;

public partial class TestPanel
{
    [SerializeField]
    public CompsData Comps = new CompsData();

    [System.Serializable]
    public class CompsData
    {
        public Image imgTest;
        public Button btnTest;
        public Button btnClose;
        public TMP_Text txtTest;
    }
}
