// Auto-generated by UIBinder, do not edit manually
// Regenerate by clicking "Export Code" on UIBinder component

using UnityEngine;
using UnityEngine.UI;
using TMPro;
using Framework.UI;

public partial class ShopPanel
{
    [System.NonSerialized] public CompsData comps = new CompsData();

    [System.Serializable]
    public class CompsData : CompsDataBase
    {
        public ScrollList listShopCard;
        public Button btnContinue;
        public Button btnDeleteCard;
        public TMP_Text txtDeletePrice;
        public TMP_Text txtDeleteCount;
    }
}
