// Auto-generated by UIBinder, do not edit manually
// Regenerate by clicking "Export Code" on UIBinder component

using UnityEngine;
using UnityEngine.UI;
using TMPro;
using Framework.UI;

public partial class ShopCardItem
{
    [System.NonSerialized] public CompsData comps = new CompsData();

    [System.Serializable]
    public class CompsData : CompsDataBase
    {
        public Button btnCard;
        public TMP_Text txtCoin;
    }
}
